---
title: "Jinxia Zou's STA 9750 Website"
---

Welcome to my course website for **STA 9750: Software Tools for Data Analysis** at Baruch College!

## About Me

I am a graduate student passionate about data analytics and business applications. This site will host my mini-projects and course project throughout the semester.

Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/jinxia-zou-874987274).

```{r}
#| include: false
1+1
```
--------------
Last Updated: `r format(Sys.time(), "%A %m %d, %Y at %H:%M%p")`

```{r}
#| echo: false
#| message: false
#| warning: false

if(!require("leaflet")){
    options(repos=c(CRAN="https://cloud.r-project.org"))
    install.packages("leaflet")
    stopifnot(require("leaflet"))
}

baruch_longitude <- -73.98333
baruch_latitude  <- +40.74028

leaflet() |>
  addTiles() |>
  setView(baruch_longitude, baruch_latitude, zoom=17) |>
  addPopups(baruch_longitude, baruch_latitude, 
            "I am a Master's student at <b>Baruch College</b>!")
```
